### PR TITLE
Use github.com/rsjethani/sysinfo package

### PR DESCRIPTION
**Pull request by rsjethani**
Use this package to get information from the Kernel instead of external commands

Resolves: Issue #1

### CODE REVIEW

**Comment by meysampg** [comment]
@rsjethani 
I love your attitude on the development of `sysinfo` package. Thanks!
:heart:

**Comment by rsjethani** [comment]
@meysampg thank you :)
It's just a start hoping to make that project into something very useful.

**Comment by meysampg** [comment]
@rsjethani Can you add a vendor system like `gomodule`, `dep` or `glide` to the project?

**Comment by rsjethani** [comment]
@meysampg to sysinfo?

**Comment by meysampg** [comment]
@rsjethani to `battery_notifier`.

**Comment by rsjethani** [comment]
@meysampg ok sure will do. Also i think should remove -d and -n options. Its a small project so -d doesn't makes sense. And since we always intend to send notification -n is redundant.

**Comment by meysampg** [comment]
@rsjethani Thanks, dude.
`-n` is not redundant. I think there are situations which result from this utility will be used on shell scripting.

**Comment by rsjethani** [comment]
@meysampg if i run without any options, i do not get any output. Are you planning to add something to the project that will make it usable in shell script?

**Comment by meysampg** [comment]
@rsjethani I do, but currently, I'm very busy on my office and can't do that.
But you're right, it's annoying to use `-n` every time, so we can change this behavior, in the default manner if no `-n` is given, send a notification, otherwise send output to the CLI.
What's your opinion?

**Comment by rsjethani** [comment]
@meysampg if you are planning to use this in some script then let's keep -n explicitly for desktop notification i.e. the same behaviour as of now.

**Comment by meysampg** [comment]
@rsjethani If you think it's okay, it's okay :wink:.

**Comment by rsjethani** [comment]
@meysampg you said you want to write a script around this. What exactly are you trying to achieve?

**Comment by meysampg** [comment]
@rsjethani to be honest, it's a vague imagination :smile:.

**Comment by rsjethani** [comment]
@meysampg this is what I want:
Continuously monitor battery status but only start notifying when battery percentage < threshold. And keep sending notification every few minutes. I will make a system service out of this.

I desired this functionality because current linux desktop environments do not send such notifications..many a times my laptop just powered down itself in the middle of a movie(no notifications or battery status in full screen) :smile: 

Next PR will complete this (my) requirement while keeping current functionality the way it is.

**Comment by meysampg** [comment]
@rsjethani The major purpose of this repository exactly was what you said :smile:. `i3wm` doesn't send any notice on the low battery situations and for me, that was like drinking a cup of very cold coffee :smile:.

**Pull request merged**
