### PR TITLE
Introduce Battery Watch Functionality

### PR DESCRIPTION
**Pull request by rsjethani**
If `argWatch` (-w option) is given then:

* Check battery after every `argLowInternval` minutes (-l option) if battery is
  below threshold.
* Check battery after every `argNormalInternval` minutes (-n option) if battery is
  above threshold.
* Print current battery capacity and state and send a desktop notification.

Else:
 Just print current battery capacity and state and exit.

### CODE REVIEW

**Comment by meysampg** [comment]
Thanks dude :heart: :smiley:.

**Comment by rsjethani** [comment]
created following systemd service:
```
[Unit]
Description=System Battery Monitor and Notifier
After=multi-user.target

[Service]
User=ryan
ExecStart=/usr/local/bin/battery_notifier -w
Restart=on-failure
RestartSec=30s

[Install]
WantedBy=multi-user.target
```

**Comment by meysampg** [comment]
Thanks! :heart: :musical_note: 
We should update `README` with new features!

**Comment by rsjethani** [comment]
I have a few small tweaks planned, after that lets update README and you can release v2.0

**Comment by meysampg** [comment]
@rsjethani Thanks dude :heart:.

**Pull request merged**
